### ISSUE TITLE
incompatible with cotton-client-commands 0.3

### ISSUE THREAD

**Issue by geniiii** [gbl/Grid#4]
https://pastebin.com/Adyis2RR

**Comment by Ristovski** [comment]
@geniiii Why did you close this? Issue seems to be present when using mods like https://www.curseforge.com/minecraft/mc-mods/ash-another-simple-hud

**Comment by gbl** [comment]
Ristovskii, the problem is that cotton-client-commands 0.2, which the original Grid used, is fundamentally incompatible with cotton-client-commands 0.3. You can't mix mods that use ccc 0.2 with ccc 0.3, period.

Because of this, I added a 1.14 version to be used with other mods that use ccc 0.3 here: https://www.curseforge.com/minecraft/mc-mods/grid/files/2705903

That was back on May 1st, 2019, so geniii closed the issue 2 days later.

**Comment by Ristovski** [comment]
@gbl Ah, I have somehow missed that version! Thanks
